<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "client".
 *
 * @property int $id
 * @property string $fio fio
 * @property string $phone phone
 * @property int $region_id regions
 * @property int $district_id districts
 * @property string $address address
 *
 * @property Districts $district
 * @property Regions $region
 * @property OrderAccount[] $orderAccounts
 * @property OrderAccountHistory[] $orderAccountHistories
 */
class Client extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'client';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['region_id', 'district_id', 'is_worker', 'created_by', 'worker_user_id', 'is_partner', 'type', 'is_profit_loss'], 'integer'],
            [['keshbek'], 'number'],
            [['fio', 'phone', 'address'], 'string', 'max' => 250],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['worker_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['worker_user_id' => 'id']],
            [['district_id'], 'exist', 'skipOnError' => true, 'targetClass' => Districts::className(), 'targetAttribute' => ['district_id' => 'id']],
            [['region_id'], 'exist', 'skipOnError' => true, 'targetClass' => Regions::className(), 'targetAttribute' => ['region_id' => 'id']],
            [['fio', 'total_debt', 'phone'],'required'],
            ['phone', 'unique', 'message' => 'Bu mijoz tizimda mavjud'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fio' => 'FIO',
            'phone' => 'Telefon nomer',
            'region_id' => 'Viloyat',
            'district_id' => 'Tuman',
            'address' => 'Manzil',
            'total_debt' => 'Qarzi ($)',
            'keshbek' => 'Keshbek (%)',
            'is_worker' => 'Is Worker',
            'created_by' => 'Kim qo\'shgan',
            'worker_user_id' => 'Mas\'ul xodim',
            'is_partner' => 'Hamkor',
            'type' => 'Mijoz turi',
            'is_profit_loss' => 'Foyda/Zarar hisoblanmasinmi?',
        ];
    }

    public function beforeSave($insert)
    {   
        // $this->cr_date = date('Y-m-d H:i:s');
        // $this->cr_date_time = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->is_worker = 0;
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    
    public function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Oddiy mijoz',],
            ['id' => '2', 'type' => 'Bozordagi mijoz',],
            ['id' => '3', 'type' => 'Filial',],
        ],
        'id', 'type');
    }

    public function getTypeView($id)
    {
        if($id == 1) return 'Oddiy mijoz';
        if($id == 2) return 'Bozordagi mijoz';
        if($id == 3) return 'Filial';
    }

    public function getTypeNameView($name)
    {
        if($name == 'Oddiy mijoz') return 1;
        if($name == 'Bozordagi mijoz') return 2;
        if($name == 'Filial') return 3;
    }

    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    public function getWorkerUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'worker_user_id']);
    }

    public function getWorkerUsers()
    {
        return ArrayHelper::map(
            Users::find()
                ->select(['id', new \yii\db\Expression("CONCAT(surname, ' ', name) AS full_name")])
                ->where(['status' => Users::STATUS_ACTIVE])
                ->orderBy(['surname' => SORT_ASC, 'name' => SORT_ASC])
                ->asArray()
                ->all(),
            'id',
            'full_name'
        );
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistrict()
    {
        return $this->hasOne(Districts::className(), ['id' => 'district_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRegion()
    {
        return $this->hasOne(Regions::className(), ['id' => 'region_id']);
    }

    public function getRegions()
    {
        return ArrayHelper::map(Regions::find()->all(), 'id', 'name');
    }

    public function getDistricts($id)
    {
        return ArrayHelper::map(Districts::find()->where(['region_id' => $id])->all(), 'id', 'name');
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderAccounts()
    {
        return $this->hasMany(OrderAccount::className(), ['client_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderAccountHistories()
    {
        return $this->hasMany(OrderAccountHistory::className(), ['client_id' => 'id']);
    }

    public function getVozvratOrders()
    {
        return $this->hasMany(VozvratOrder::className(), ['client_id' => 'id']);
    }
}
