<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "debt_repayment".
 *
 * @property int $id
 * @property double $summa summa
 * @property string $text text
 * @property string $date
 * @property int $order_account_id regions
 *
 * @property OrderAccount $orderAccount
 */
class DebtRepayment extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'debt_repayment';
    }
    var $clients_id = null;
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['summa', 'sum_som', 'summ_dollar', 'summ_cart', 'sum_transfers', 'total_debt', 'exchange_rate', 'discount_amount', 'all_summ_dollar', 'total_debt_old', 'zdacha_sum', 'zdacha_dollar'], 'number'],
            [['text'], 'string'],
            [['date', 'cr_date_time'], 'safe'],
            [['order_account_id', 'client_id', 'created_by', 'is_delete', 'is_worker'], 'integer'],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['order_account_id'], 'exist', 'skipOnError' => true, 'targetClass' => OrderAccount::className(), 'targetAttribute' => ['order_account_id' => 'id']],
            [['date', 'exchange_rate'],'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'summa' => 'Summa ($)',
            'text' => 'Izoh',
            'is_delete' => 'O\'chirilsinmi?',
            'date' => 'Sana',
            'cr_date_time' => 'Yaratilgan Sana',
            'order_account_id' => 'Mijoz',
            'client_id' => 'Mijoz',
            'clients_id' => 'Mijoz',
            'sum_som' => 'Summa so\'mda',
            'summ_dollar' => 'Summa dollarda ($)',
            'summ_cart' => 'Summa kartada',
            'sum_transfers' => 'Summa transferda',
            'total_debt' => 'Jami qarz ($)',
            'exchange_rate' => 'Dollar kursi',
            'discount_amount' => 'Jami chegirma ($)',
            'all_summ_dollar' => 'Umumiy summa ($)',
            'created_by' => 'Qarzni olgan Xodim',
            'total_debt_old' => 'Jami qarz ($)',
            'is_worker' => 'Ishchilar Qarzi',
            'zdacha_sum' => 'Qaytim so\'mda',
            'zdacha_dollar' => 'Qaytim',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->date != null ) $this->date = \Yii::$app->formatter->asDate($this->date, 'php:Y-m-d');

        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
            $this->cr_date_time = date('Y-m-d H:i:s');
            $this->is_delete = 0;
            $this->is_worker = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrderAccount()
    {
        return $this->hasOne(OrderAccount::className(), ['id' => 'order_account_id']);
    }

    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    public function getClients()
    {
        return ArrayHelper::map(Client::find()->all(), 'id', 'fio');
    }

    public function getInvoiceHtmlTextSklad($model, $id)
    {
        $about = About::find()->where(['id' => 1])->one();
        $tulan_sum_som = $model->sum_som?'To\'langan summa so\'mda:': '';
        $tulan_sum_karta = $model->summ_cart?'To\'langan summa kartada:': '';
        $tulan_sum_transfer = $model->sum_transfers?'To\'langan summa transferda:': '';
        $discount_amount_sum = $model->discount_amount?'Jami chegirma ($):': '';
        $discount_amount_sum_val = $model->discount_amount?$model->discount_amount.' $,': '';
        $text = '   
          
        <table style="width: 100%; text-align: right; font-size:12px">  
             <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px;">{date}<br/></b></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px; color:red;">{customer_fio}<br/></b></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><hr></td>
            </tr>
            <tr>
                <td rowspan="5" style="text-align: left; width: 150px!important;"><img src="../views/image/logo4.jpg" style="height:100px; border-radius:20%;"></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 200px;">Do\'kon:</th>
                <td  ><b >{t_p},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;font-size:14px; color:green;">Dollar kursi:</th>
                <td ><b style="text-align: left;font-size:14px; color:green;">{exchange_rate} so\'m</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left;">Firma:</th>
                <td ><b >{postavshik},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left; width: 150px;">Manzil:</th>
                <td ><b >{customer_region}, {customer_district}</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 150px;">Telefon nomer:</th>
                <td ><b >{phone},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;">Telefon:</th>
                <td   ><b >{customer_phone}</b></td>
            </tr>
            <tr>                            
        </table>
        <hr>
        <br>
            <table style="width: 100%; text-align: right; font-size:12px">   
                <tr>
                    <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:16px;">To\'langan qarz hisobi:<br/></b><br><br></td>
                </tr>
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 250px;color:#f59c1">Ostatka  ($):</th>
                    <td ><b style="font-size:16px;color:#f59c1">{total_debt_old} $,</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0">To\'langan summa dollarda ($):</th>
                    <td ><b style="color:#474ba0">{summ_dollar} $</b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;color:#f59c1">'.$discount_amount_sum.'</th>
                    <td ><b style="color:#f59c1" >'.$discount_amount_sum_val.'</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left;color:#474ba0"></th>
                    <td  ><b style="color:#474ba0"></b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;color:#f59c1">Jami to\'langan summa ($):</th>
                    <td ><b style="color:#f59c1" >{all_summ_dollar} $,</b></td>

                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0"></th>
                    <td ><b style="color:#474ba0"> </b></td>
                </tr>
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 150px;color:red">Qolgan qarz ($): </th>
                    <td ><b style="font-size:16px;color:red" >{total_debt} $,</b></td>
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left;color:#474ba0"></th>
                    <td><b style="color:#474ba0"></b></td>
                </tr>                         
            </table>
      ';
        $text = str_replace ("{sum_som}", $model->sum_som?Yii::$app->formatter->asDecimal($model->sum_som,2):' ' , $text);
        $text = str_replace ("{summ_dollar}", $model->summ_dollar?Yii::$app->formatter->asDecimal($model->summ_dollar,2): '0' , $text);
        $text = str_replace ("{summ_cart}", $model->summ_cart?Yii::$app->formatter->asDecimal($model->summ_cart,2):' ' , $text);
        $text = str_replace ("{sum_transfers}", $model->sum_transfers?Yii::$app->formatter->asDecimal($model->sum_transfers,2):' ' , $text);
        $text = str_replace ("{total_debt}", $model->total_debt?Yii::$app->formatter->asDecimal($model->total_debt,2):'0' , $text);
        $text = str_replace ("{total_debt_old}", $model->total_debt_old?Yii::$app->formatter->asDecimal($model->total_debt_old,2):'0' , $text);
        $text = str_replace ("{exchange_rate}", $model->exchange_rate?Yii::$app->formatter->asDecimal($model->exchange_rate,0):' ' , $text);
        $text = str_replace ("{discount_amount}", $model->discount_amount?Yii::$app->formatter->asDecimal($model->discount_amount, 2):'0' , $text);
        $text = str_replace ("{all_summ_dollar}", $model->all_summ_dollar?Yii::$app->formatter->asDecimal($model->all_summ_dollar, 2):'0' , $text);
        $text = str_replace ("{zdacha_dollar}", $model->zdacha_dollar?Yii::$app->formatter->asDecimal($model->zdacha_dollar, 2):'0' , $text);
        $text = str_replace ("{zdacha_sum}", $model->zdacha_sum?Yii::$app->formatter->asDecimal($model->zdacha_sum, 2):'0' , $text);
        $text = str_replace ("{date}", $model->date , $text);

        $text = str_replace ("{order_account_id}", $model->order_account_id , $text);
        $text = str_replace ("{customer_fio}", $model->client->fio , $text);
        $text = str_replace ("{customer_phone}", $model->client->phone , $text);
        $text = str_replace ("{customer_region}", $model->client->region_id?$model->client->region->name:'' , $text);
        $text = str_replace ("{customer_district}", $model->client->district_id?$model->client->district->name:'' , $text);

        $text = str_replace ("{nomer_nakladnoy}", $about->nomer_nakladnoy , $text);
        $text = str_replace ("{postavshik}", $about->postavshik , $text);
        $text = str_replace ("{phone}", $about->phone , $text);
        $text = str_replace ("{dostavshik}", $about->dostavshik , $text);
        $text = str_replace ("{t_p}", $about->t_p , $text);

        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }
}
