<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "elegant_history_update".
 *
 * @property int $id
 * @property int $client_id clients
 * @property int $order_account_id order account
 * @property int $order_account_history_id order account history
 * @property int $debt_repayment_id debt-repayment
 * @property int $product_category_id product-category
 * @property int $brand_id brands
 * @property string $comment Comment
 * @property string $cr_date
 * @property int $created_by create user
 * @property int $user_id update user
 *
 * @property Brands $brand
 * @property Client $client
 * @property Users $createdBy
 * @property DebtRepayment $debtRepayment
 * @property OrderAccountHistory $orderAccountHistory
 * @property OrderAccount $orderAccount
 * @property ProductCategory $productCategory
 * @property Users $user
 */
class ElegantHistoryUpdate extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'elegant_history_update';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_by', 'status', 'order_account_history_id', 'type'], 'integer'],
            [['comment', 'title'], 'string'],
            [['cr_date'], 'safe'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Sarlavha',
            'comment' => 'Izoh',
            'cr_date' => 'O\'gargan sana',
            'status' => 'Turi',
            'created_by' => 'Kim o\'zgartirdi',
            'order_account_history_id' => '',
            'type' => 'O\'zgarish bo\'lgan joy',
        ];
    }
    public function beforeSave($insert)
    {   
        // $this->cr_date = date('Y-m-d H:i:s');
        // $this->cr_date_time = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->cr_date = date('Y-m-d H:i:s');
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    public static function getStatus()
    {
        return ArrayHelper::map([
            ['id' => '1', 'status' => 'O\'zgartirildi',],
            ['id' => '2', 'status' => 'O\'chirildi',],
            ['id' => '3', 'status' => 'Qarz to\'landi',],
            ['id' => '4', 'status' => 'Boshqa',],
        ],
        'id', 'status');
    }

    public function getStatusView($id)
    {
        if($id == 1) return 'O\'zgartirildi';
        if($id == 2) return 'O\'chirildi';
        if($id == 3) return 'Qarz to\'landi';
        if($id == 4) return 'Boshqa';
    }

    public static function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'status' => 'Ombor',],
            ['id' => '2', 'status' => 'Do\'kon',],
        ],
        'id', 'status');
    }

    public function getTypeView($id)
    {
        if($id == 1) return 'Ombor';
        if($id == 2) return 'Do\'kon';
    }

}
