<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "expenses".
 *
 * @property int $id
 * @property string $nomi nomi
 * @property double $summa summa
 * @property string $date_cr
 * @property int $type_id type_id
 * @property int $loss_of_profit_id loss_of_profit
 *
 * @property LossOfProfit $lossOfProfit
 * @property TypeExpense $type
 */
class Expenses extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'expenses';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['summa'], 'number'],
            [['date_cr'], 'safe'],
            [['type_id', 'loss_of_profit_id'], 'integer'],
            [['nomi'], 'string', 'max' => 250],
            [['loss_of_profit_id'], 'exist', 'skipOnError' => true, 'targetClass' => LossOfProfit::className(), 'targetAttribute' => ['loss_of_profit_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => TypeExpense::className(), 'targetAttribute' => ['type_id' => 'id']],
            [['nomi', 'summa', 'type_id'],'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nomi' => 'Nomi',
            'summa' => 'Summa ($)',
            'date_cr' => 'Sana',
            'type_id' => 'Turi',
            'loss_of_profit_id' => 'Loss Of Profit ID',
        ];
    }
    public function beforeSave($insert)
    {
        if($this->date_cr != null ) $this->date_cr = \Yii::$app->formatter->asDate($this->date_cr, 'php:Y-m-d');
        
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLossOfProfit()
    {
        return $this->hasOne(LossOfProfit::className(), ['id' => 'loss_of_profit_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(TypeExpense::className(), ['id' => 'type_id']);
    }

    public function getTypes()
    {
        return ArrayHelper::map(TypeExpense::find()->all(), 'id', 'name');
    }
}
