<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "loss_of_profit".
 *
 * @property int $id
 * @property double $profit profit
 * @property double $loss loss
 * @property string $date_end
 * @property string $date_start
 * @property int $created_by create user
 *
 * @property Expenses[] $expenses
 * @property Users $createdBy
 */
class LossOfProfit extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'loss_of_profit';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['profit', 'loss'], 'number'],
            [['date_end', 'date_start'], 'safe'],
            [['created_by'], 'integer'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['date_end', 'date_start'],'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'profit' => 'Foyda $',
            'loss' => 'Zarar $',
            'date_end' => 'Oxirgi sana',
            'date_start' => 'Boshlanish sana',
            'created_by' => 'Kim tomonidan',
        ];
    }

    public function beforeSave($insert)
    {   
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getExpenses()
    {
        return $this->hasMany(Expenses::className(), ['loss_of_profit_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }
}
