<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "my_total_debt".
 *
 * @property int $id
 * @property string $cr_date
 * @property double $total_debt total debt
 * @property int $consignor_id consignor
 * @property int $created_by create user
 * @property int $update_by update user
 *
 * @property Consignor $consignor
 * @property Users $createdBy
 * @property Users $updateBy
 * @property MyTotalDebtHistory[] $myTotalDebtHistories
 */
class MyTotalDebt extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'my_total_debt';
    }

    /**
     * {@inheritdoc}
     */
    var $comment = null;
    var $total_debts = null;
    var $chegirma = null;

    public function rules()
    {
        return [
            [['cr_date'], 'safe'],
            [['total_debt'], 'number'],
            [['consignor_id', 'created_by', 'update_by'], 'integer'],
            [['consignor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Consignor::className(), 'targetAttribute' => ['consignor_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['update_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['update_by' => 'id']],
            [['consignor_id', 'total_debt'],'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cr_date' => 'Oxirgi o\'zgargan sana',
            'total_debt' => 'Qarz miqdori ($)',
            'consignor_id' => 'Yuk jo\'natuvchi',
            'created_by' => 'Kim tomonidan',
            'update_by' => 'Kim tomonidan',
            'comment' => 'Izoh',
            'chegirma' => 'Chegirma ($)',
            'total_debts' => 'Qarz miqdori ($)',
        ];
    }
    public function beforeSave($insert)
    {   
        // $this->cr_date = date('Y-m-d H:i:s');
        // $this->cr_date_time = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->update_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsignor()
    {
        return $this->hasOne(Consignor::className(), ['id' => 'consignor_id']);
    }
    public function getConsignor1()
    {
        return ArrayHelper::map(Consignor::find()->all(), 'id', 'name');
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdateBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'update_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMyTotalDebtHistories()
    {
        return $this->hasMany(MyTotalDebtHistory::className(), ['my_total_debt_id' => 'id']);
    }
}
