<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "my_total_debt_history".
 *
 * @property int $id
 * @property string $cr_date
 * @property double $total_debt total debt
 * @property double $discount_amount discount amount
 * @property int $my_total_debt_id my total debt
 * @property int $created_by create user
 * @property int $update_by update user
 *
 * @property Users $createdBy
 * @property MyTotalDebt $myTotalDebt
 * @property Users $updateBy
 */
class MyTotalDebtHistory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'my_total_debt_history';
    }

    var $all_total_debt_sum = null;

    public function rules()
    {
        return [
            [['cr_date'], 'safe'],
            [['total_debt', 'discount_amount', 'exchange_rate', 'all_summ_dollar'], 'number'],
            [['my_total_debt_id', 'created_by', 'update_by'], 'integer'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['my_total_debt_id'], 'exist', 'skipOnError' => true, 'targetClass' => MyTotalDebt::className(), 'targetAttribute' => ['my_total_debt_id' => 'id']],
            [['update_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['update_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cr_date' => 'Sana',
            'total_debt' => 'Summa ($)',
            'all_total_debt_sum' => 'Qolgan qarzim ($)',
            'exchange_rate' => 'Qolgan qarzim ($)',
            'all_summ_dollar' => 'Umumiy summa ($)',
            'discount_amount' => 'Chegirma ($)',
            'my_total_debt_id' => 'My Total Debt ID',
            'created_by' => 'Kim tomonidan',
            'update_by' => 'Update By',
        ];
    }

    public function beforeSave($insert)
    {   
        // $this->cr_date = date('Y-m-d H:i:s');
        // $this->cr_date_time = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMyTotalDebt()
    {
        return $this->hasOne(MyTotalDebt::className(), ['id' => 'my_total_debt_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdateBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'update_by']);
    }

    public function getInvoiceHtmlTextSklad($model, $id)
    {
        $about = About::find()->where(['id' => 1])->one();
        $myTotalDebt = MyTotalDebt::find()->where(['id' => $model->my_total_debt_id])->one();
        $discount_amount_sum = $model->discount_amount?'Jami chegirma ($):': '';
        $discount_amount_sum_val = $model->discount_amount?$model->discount_amount.' $,': '';
        $text = '   
          
        <table style="width: 100%; text-align: right; font-size:12px">  
             <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px;">{date}<br/></b></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px; color:red;">{customer_fio}<br/></b></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><hr></td>
            </tr>
            <tr>
                <td rowspan="5" style="text-align: left; width: 150px!important;"><img src="../views/image/logo4.jpg" style="height:100px; border-radius:20%;"></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 200px;">Do\'kon:</th>
                <td  ><b >{t_p},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left; font-size:12px;width: 150px;color:green;">Mijoz telefon:</th>
                <td ><b style="color:green;font-size:12px;">{customer_phone}</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left;">Firma:</th>
                <td ><b >{postavshik},</b></td>
                <td style="width: 10px;"></td>
                
                <th nowrap style="text-align: left;font-size:12px; color:green;">Mijoz manzil:</th>
                <td ><b style="text-align: left;font-size:12px; color:green;">{customer_address} </b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 150px;">Telefon nomer:</th>
                <td ><b >{phone},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;"></th>
                <td   ><b ></b></td>
            </tr>
            <tr>                            
        </table>
        <hr>
        <br>
            <table style="width: 100%; text-align: right; font-size:12px">   
                <tr>
                    <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:16px;">To\'langan qarzim hisobi:<br/></b><br><br></td>
                </tr>
                <tr>
                    <th nowrap style="font-size:16px;text-align: left;color:#f59c1">Ostatka  ($):</th>
                    <td ><b style="font-size:16px;color:#f59c1">{total_debt_old} $,</b></td>
                    
                </tr>
                <tr>
                    <th nowrap style="text-align: left; color:#f59c1">Jami to\'langan summa ($):</th>
                    <td ><b style="color:#f59c1" >{all_summ_dollar} $,</b></td>

                </tr>
                <tr>
                    <th nowrap style="text-align: left; color:#f59c1">'.$discount_amount_sum.'</th>
                    <td ><b style="color:#f59c1" >'.$discount_amount_sum_val.'</b></td>
                    
                </tr>
                
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; color:red">Qolgan qarz ($): </th>
                    <td ><b style="font-size:16px;color:red" >{total_debt} $,</b></td>
    
                </tr>                         
            </table>
      ';


        $text = str_replace ("{total_debt_old}", $model->total_debt?Yii::$app->formatter->asDecimal($model->total_debt,2):'0' , $text);
        $text = str_replace ("{total_debt}", $model->exchange_rate?Yii::$app->formatter->asDecimal($model->exchange_rate,2):' ' , $text);
        $text = str_replace ("{exchange_rate}", $model->exchange_rate?Yii::$app->formatter->asDecimal($model->exchange_rate,0):' ' , $text);
        $text = str_replace ("{discount_amount}", $model->discount_amount?Yii::$app->formatter->asDecimal($model->discount_amount, 2):' ' , $text);
        $text = str_replace ("{all_summ_dollar}", $model->all_summ_dollar?Yii::$app->formatter->asDecimal($model->all_summ_dollar, 2):' ' , $text);
        $text = str_replace ("{date}", $model->cr_date , $text);

        $text = str_replace ("{customer_fio}", $myTotalDebt->consignor->name , $text);
        $text = str_replace ("{customer_phone}", $myTotalDebt->consignor->phone , $text);
        $text = str_replace ("{customer_address}", $myTotalDebt->consignor->address , $text);

        $text = str_replace ("{nomer_nakladnoy}", $about->nomer_nakladnoy , $text);
        $text = str_replace ("{postavshik}", $about->postavshik , $text);
        $text = str_replace ("{phone}", $about->phone , $text);
        $text = str_replace ("{dostavshik}", $about->dostavshik , $text);
        $text = str_replace ("{t_p}", $about->t_p , $text);

        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }

}
