<?php

namespace app\models;
use yii\helpers\Html;
use Yii;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property string $customer_fio customer fio
 * @property int $brand_id Brands
 * @property int $product_category_id Product category
 * @property double $size Size
 * @property int $count Count
 * @property string $cr_date
 * @property string $cr_print_date
 * @property int $created_by create user
 * @property int $update_by update user
 *
 * @property Brands $brand
 * @property Users $createdBy
 * @property ProductCategory $productCategory
 * @property Users $updateBy
 */
class Orders extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'orders';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_by', 'update_by', 'status'], 'integer'],
            [['cr_date', 'cr_date_time'], 'safe'],
            [['customer_fio', 'order_number'], 'string', 'max' => 255],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['update_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['update_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_number' => 'Buyurtma raqami',
            'customer_fio' => 'Buyurtmachi ismi',
            'cr_date' => 'Buyurtma qilingan sana',
            'cr_date_time' => 'Buyurtma qilingan sana',
            'created_by' => 'Kim yaratdi',
            'update_by' => 'Kim o\'zgartirdi',
            'status' => 'Holati',
        ];
    }

    public function beforeSave($insert)
    {   
        $this->cr_date = date('Y-m-d H:i:s');
        $this->order_number = '#' . $random = substr(number_format(time() * rand(),0,'',''),0,8);
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    public function getYearsList()
    {
        $result = [
            2018 => "2018",
            2019 => "2019",
            2020 => "2020",
            2021 => "2021",
            2022 => "2022",
            2023 => "2023",
            2024 => "2024",
            2025 => "2025",
            2026 => "2026",
            2027 => "2027",
            2028 => "2028",
            2029 => "2029",
            2030 => "2030",
        ];
        return $result;
    }
    
    public function getStatus()
    {
        return ArrayHelper::map([
            ['id' => '1', 'status' => 'Sotilgan',],
            ['id' => '2', 'status' => 'Bekor qilingan',],
        ],
        'id', 'status');
    }

    public function getUpdateBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'update_by']);
    }

    public function getInvoiceHtmlText($model, $id)
    {
        $warehouse = OrderProducts::find()->where(['order_id' => $id])->select(['brand_id'])->groupBy(['brand_id'])->all();
        $table = '';
        $allCount = 0;
        $table .= '<table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                    <tr style="">
                        <td style="height: 20px;text-align: center; width: 20%; border: 1px solid #000;"><b>MODEL</b></td>
                        <td style="height: 20px;text-align: center; width: 20%; border: 1px solid #000;"><b>NOMI</b></td>
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>+</b></td>
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>SONI</b></td>
                    </tr>';
        foreach ($warehouse as $model1) { 
            foreach ($orderProduct = OrderProducts::find()->andWhere(['order_id' => $id])->andWhere(['brand_id' => $model1->brand_id])->all() as $model1){ 
                $table .= '<tr style="">
                            <td style="height: 30px; border: 1px solid #000;"><b>&nbsp;'. $model1->brand->name . '</b></td>
                            <td style="height: 30px; border: 1px solid #000;"><b>&nbsp;'. $model1->productCategory->name.($model1->size!='0'?'&nbsp; (&nbsp;'. $model1->size.'&nbsp;)' : '') . '</b></td>
                            <td style="height: 30px; border: 1px solid #000;">&nbsp;</td>
                            <td style="height: 30px; text-align: center; border: 1px solid #000;"><b>'. $model1->count . '</b></td>
                        </tr>';
                $allCount = $allCount + $model1->count;
            }
            $table .= '<tr style="">
                            <td colspan="4" style="height: 30px; border: 1px solid #000;">&nbsp;</td>
                            
                        </tr>';
        }
        $table .= '
                    <tr style="">
                        <td colspan="3" style=";height: 30px; border: 1px solid #000;">&nbsp;<b>Jami</b></td>

                        <td style="height: 30px; text-align: center; border: 1px solid #000;"><b>'. $allCount . '</b></td>
                    </tr>
        </table>';

        $text = '   
          <br/>
        <p style="width: 100%; margin-top: -10px; text-align: left;"><b>Buyurtma raqami:</b> {order_number}</p>  
        <table style="width: 100%;">
            <tr>
                <td style="width: 600px; padding-left: 0;"><b>Mijoz:</b> {customer_fio} </td>
                <td style="width: 150px"> {cr_date}</td>
            </tr>
        </table> 
        '.$table.'
       
        <table style="margin-top: 30px; width: 100%;">
            <tr>
                <td style="width: 35%; padding-left: 0;">Shafyor: </td>
                <td style="width: 65%; text-align: left; border-bottom: 1px solid #000;"></td>
            </tr>
        </table> 
      ';
        

        $text = str_replace ("{order_number}", $model->order_number , $text);
        $text = str_replace ("{customer_fio}", $model->customer_fio , $text);
        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }
}
