<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;
use app\models\TypeSklad;
/**
 * This is the model class for table "order_account".
 *
 * @property int $id
 * @property int $client_id client
 * @property string $date
 * @property double $exchange_rate dollar exchange rate
 * @property double $discount_amount сумма скидки
 * @property double $all_summ_dollar all_summ_dollar
 * @property double $all_profit_dollar all_profit_dollar
 * @property double $total_debt total debt
 * @property string $date_last_debt_payment
 * @property double $number_of_orders number_of_orders
 * @property string $last_order_date
 * @property double $sum_som sum_som
 * @property double $sum_dollar summ_dollar
 * @property double $sum_cart summ_cart
 * @property double $sum_transfers summ_transfers
 * @property int $created_by create user
 * @property string $cr_date
 *
 * @property DebtRepayment[] $debtRepayments
 * @property Client $client
 * @property Users $createdBy
 * @property ProductAccount[] $productAccounts
 */
class OrderAccount extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'order_account';
    }

    /**
     * {@inheritdoc}
     */
    var $clients_id = null;
    var $dates = null;
    var $total_debts = null;
    var $exchange_rates = null;
    var $comment = null;

    var $discount_amounts = null;
    var $sum_dollars = null;
    var $sum_soms = null;
    var $dollar_sumdas = null;
    var $sum_carts = null;
    var $sum_transferss = null;
    var $order_account_statuses = null;
    var $sum_all_pro = null;
    public function rules()
    {
        return [
            [['client_id', 'created_by', 'is_worker'], 'integer'],
            [['date', 'date_last_debt_payment', 'last_order_date', 'cr_date', 'cr_date_time'], 'safe'],
            [['exchange_rate', 'all_product_sum', 'discount_amount', 'all_summ_dollar', 'all_profit_dollar', 'total_debt', 'total_debt_old', 'number_of_orders', 'dollar_sumda', 'sum_som', 'sum_dollar', 'sum_cart', 'sum_transfers'], 'number'],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            // [['dates', 'clients_id', 'exchange_rates'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_id' => 'Mijoz',
            'clients_id' => 'Mijoz',
            'dates' => 'Sana',
            'date' => 'Sana',
            'all_product_sum' => 'Umumiy summa ($)',
            'exchange_rates' => 'Dollar kursi',
            'exchange_rate' => 'Dollar kursi',
            'discount_amount' => 'Jami chegirma ($)',
            'all_summ_dollar' => 'Jami to\'langan summa ($)',
            'all_profit_dollar' => 'Jami foyda ($)',
            'total_debt' => 'Jami qarz ($)',
            'total_debts' => 'Jami qarz ($)',
            'total_debt_old' => 'Eski qarz ($)',
            'date_last_debt_payment' => 'Oxirgi qarzni to\'lash sanasi',
            'number_of_orders' => 'Buyurtmalar soni',
            'last_order_date' => 'Oxirgi buyurtma sanasi',
            'sum_som' => 'Summa so\'mda',
            'sum_dollar' => 'Summa dollarda ($)',
            'sum_cart' => 'Summa kartada',
            'sum_transfers' => 'Summa transferda',
            'dollar_sumda' => 'Dollar so\'mda qiymati',

            'discount_amounts' => 'Jami chegirma ($)',
            'sum_soms' => 'Summa so\'mda',
            'dollar_sumdas' => 'So\'m dollarda',
            'sum_dollars' => 'Summa dollarda ($)',
            'sum_carts' => 'Summa kartada',
            'sum_transferss' => 'Summa transferda',
            'sum_all_pro' => '',
            'order_account_statuses' => '',

            'created_by' => 'Kim tomonidan ',
            'cr_date' => 'Yaratilgan vaqt',
            'cr_date_time' => 'Yaratilgan vaqt',
            'comment' => 'Izoh',
            'is_worker' => 'Ishchilar zakazi',
        ];
    }

    public function beforeSave($insert)
    {   
        // $this->cr_date = date('Y-m-d H:i:s');
        // $this->cr_date_time = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
            $this->is_worker = 0;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDebtRepayments()
    {
        return $this->hasMany(DebtRepayment::className(), ['order_account_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }
    public function getClients()
    {
        return ArrayHelper::map(Client::find()->all(), 'id', 'fio');
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductAccounts()
    {
        return $this->hasMany(ProductAccount::className(), ['order_account_id' => 'id']);
    }
    
    public function getBrands()
    {
        return ArrayHelper::map(Brands::find()->where(['sup_status' => 1])->all(), 'id', 'name');
    }

    public function getProductCategories()
    {
        return ArrayHelper::map(ProductCategory::find()->where(['sup_status' => 1])->all(), 'id', 'name');
    }
    
    public function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }

    public function getTypeNameView($name)
    {
        if($name == 'Dona') return 1;
        if($name == 'Karobka') return 2;
        if($name == 'Komplekt') return 3;
        if($name == 'Pochka') return 4;
    }
    
    public function getTypeView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }
    public function getTypeSklads()
    {
        return ArrayHelper::map(TypeSklad::find()->all(), 'id', 'name');
    }
    public function getInvoiceHtmlText($model, $id)
    {
        $warehouse = ProductAccount::find()->where(['order_account_id' => $id])->select(['brand_id'])->groupBy(['brand_id'])->all();
        $orderAccount2 = OrderAccount::find()->where(['client_id' => $model->client_id])->one();
        $about = About::find()->where(['id' => 1])->one();
        $table = '';
        $allCount = 0;
        $allSumm = 0;
        $tulan_sum_som = $model->sum_som?'To\'langan summa so\'mda:': '';
        $tulan_sum_karta = $model->sum_cart?'To\'langan summa kartada:': '';
        $tulan_sum_transfer = $model->sum_transfers?'To\'langan summa transferda:': '';
        $discount_amount_sum = $model->discount_amount?'Jami chegirma ($):': '';
        $discount_amount_sum_val = $model->discount_amount?$model->discount_amount.' $,': '';
        $table .= '<table style="width: 100%; border-collapse: collapse; margin-top: 15px;font-size:12px">
                    <tr style="">
                        <td style="height: 20px;text-align: center; width: 10px; border: 1px solid #000;"><b>№</b></td>
                        <td style="height: 20px;text-align: center; width: 15%; border: 1px solid #000;"><b>MODEL</b></td>
                        <td style="height: 20px;text-align: center; width: 15%; border: 1px solid #000;"><b>NOMI</b></td>
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>SONI</b></td>
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>TIP</b></td> 
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>NARXI ($)</b></td>
                        <td style="height: 20px;text-align: center; width: 12%; border: 1px solid #000;"><b>UMUMIY NARXI ($)</b></td>
                    </tr>';
        $i = 1;
        foreach ($warehouse as $model1) { 
           
            foreach ($orderProduct = ProductAccount::find()->andWhere(['order_account_id' => $id])->andWhere(['brand_id' => $model1->brand_id])->all() as $model1){ 
                $table .= '<tr style="">
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $i . '</b></td>
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $model1->brand->name . '</b></td>
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $model1->productCategory->name.($model1->size!='0'?'&nbsp; (&nbsp;'. $model1->size.'&nbsp;)' : '') . '</b></td>
                            <td style="height: 15px; text-align: center; border: 1px solid #000;"><b>'. $model1->count . '</b></td>
                            <td style="height: 15px; text-align: center;  border: 1px solid #000;"><b>&nbsp;'. $model1->getTypeView($model1->type) . '</b></td>
                            <td style="height: 15px; text-align: center;  border: 1px solid #000;"><b>'. $model1->price . '</b></td>
                            <td style="height: 15px; text-align: left;  border: 1px solid #000;"><b> = '. round($model1->count * $model1->price,2) . '</b></td>
                        </tr>';
                $allCount = $allCount + $model1->count;
                $allSumm = $allSumm + $model1->count * $model1->price;
                $i=$i+1;
            }
            // $table .= '<tr style="">
            //                 <td colspan="6" style="height: 30px; border: 1px solid #000;">&nbsp;</td>
                            
            //             </tr>';
        }
        $table .= '
                    <tr style="">
                        <td colspan="4" style=";height: 15px; border: 1px solid #000;">&nbsp;<b>Jami</b></td>

                        <td style="height: 15px; text-align: center; border: 1px solid #000;"><b></b></td>
                        <td style=";height: 15px;text-align: center; border: 1px solid #000;">&nbsp;-</td>
                        <td style=";height: 15px; border: 1px solid #000;">&nbsp;&nbsp;&nbsp;<b>'. round($allSumm,2) . '</b></td>
                    </tr>
        </table>';

        $text = '   
            <table style="width: 100%; text-align: right; font-size:12px">  
                <tr>
                    <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px;">{date}<br/></b></td>
                </tr>
                <tr>
                    <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px; color:red;">{customer_fio}<br/></b></td>
                </tr>
                <tr>
                    <td colspan="6" style="text-align: center; width: 150px!important;"><hr></td>
                </tr>
                <tr>
                    <td rowspan="5" style="text-align: left; width: 150px!important;"><img src="../views/image/logo4.jpg" style="height:100px; border-radius:20%;"></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 200px;">Do\'kon:</th>
                    <td  ><b >{t_p},</b></td>
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left;font-size:14px; color:green;">Dollar kursi:</th>
                    <td ><b style="text-align: left;font-size:14px; color:green;">{exchange_rate} so\'m</b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left;">Firma:</th>
                    <td ><b >{postavshik},</b></td>
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; width: 150px;">Manzil:</th>
                    <td ><b >{customer_region}, {customer_district}</b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;">Telefon nomer:</th>
                    <td ><b >{phone},</b></td>
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left;">Telefon:</th>
                    <td   ><b >{customer_phone}</b></td>
                </tr>
                <tr>                            
            </table>
        '.$table.'
            <br>
            <table style="width: 100%; text-align: right; font-size:12px">   
                
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 250px;color:#f59c1">Ostatka  ($):</th>
                    <td ><b style="font-size:16px;color:#f59c1">{total_debt_old} $,</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0">To\'langan summa dollarda ($):</th>
                    <td ><b style="color:#474ba0">{sum_dollar} $</b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px; color:#f59c1">Olingan tavarlar summasi ($):</th>
                    <td ><b style="color:#f59c1">{all_product_sum} $,</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left;color:#474ba0"></th>
                    <td  ><b style="color:#474ba0"></b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;color:#f59c1">Jami to\'langan summa ($):</th>
                    <td ><b style="color:#f59c1" >{all_summ_dollar} $,</b></td>

                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0"></th>
                    <td ><b style="color:#474ba0"></b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;color:#f59c1">'.$discount_amount_sum.'</th>
                    <td ><b style="color:#f59c1" >'.$discount_amount_sum_val.'</b></td>
                </tr>
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 150px;color:red">Qolgan qarz ($): </th>
                    <td ><b style="font-size:16px;color:red" >{all_total_debt} $,</b></td>
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left;color:#474ba0"></th>
                    <td><b style="color:#474ba0"></b></td>
                </tr>                         
            </table>
        ';
        
    //     .'
    //     <table style="margin-top: 30px; width: 100%;">
    //         <tr>
    //             <td style="width: 35%; padding-left: 0;">Mahsulotlarni yig\'uvchi xodim: </td>
    //             <td style="width: 65%; text-align: left; border-bottom: 1px solid #000;"></td>
    //         </tr>
    //     </table> 
    //     <table style="margin-top: 30px; width: 100%;">
    //         <tr>
    //             <td style="width: 35%; padding-left: 0;">Shafyor: </td>
    //             <td style="width: 65%; text-align: left; border-bottom: 1px solid #000;"></td>
    //         </tr>
    //     </table> 
    //   ';
        
        $text = str_replace ("{exchange_rate}", $model->exchange_rate , $text);
        $text = str_replace ("{total_debt_old}", Yii::$app->formatter->asDecimal($orderAccount2->total_debt_old, 2), $text);
        $text = str_replace ("{all_total_debt}", Yii::$app->formatter->asDecimal($orderAccount2->total_debt, 2), $text);
        $text = str_replace ("{total_debt}", Yii::$app->formatter->asDecimal($model->total_debt, 2) , $text);
        $text = str_replace ("{discount_amount}", $model->discount_amount?$model->discount_amount:'0' , $text);
        $text = str_replace ("{sum_dollar}", $model->sum_dollar?Yii::$app->formatter->asDecimal($model->sum_dollar,2):'0' , $text);
        $text = str_replace ("{all_summ_dollar}", Yii::$app->formatter->asDecimal($model->all_summ_dollar,2) , $text);
        $text = str_replace ("{sum_som}", $model->sum_som?Yii::$app->formatter->asDecimal($model->sum_som,2):'' , $text);
        $text = str_replace ("{sum_transfers}", $model->sum_transfers?Yii::$app->formatter->asDecimal($model->sum_transfers,2):' ' , $text);
        $text = str_replace ("{sum_cart}", $model->sum_cart?Yii::$app->formatter->asDecimal($model->sum_cart, 2):' ' , $text);
        $text = str_replace ("{all_product_sum}", Yii::$app->formatter->asDecimal($model->all_product_sum, 2) , $text);
        $text = str_replace ("{date}", $model->date , $text);

        $text = str_replace ("{order_number}", $model->date , $text);
        $text = str_replace ("{customer_fio}", $model->client->fio , $text);
        $text = str_replace ("{customer_phone}", $model->client->phone , $text);
        $text = str_replace ("{customer_region}", $model->client->region_id?$model->client->region->name:'' , $text);
        $text = str_replace ("{customer_district}", $model->client->district_id?$model->client->district->name:'' , $text);

        $text = str_replace ("{nomer_nakladnoy}", $about->nomer_nakladnoy , $text);
        $text = str_replace ("{postavshik}", $about->postavshik , $text);
        $text = str_replace ("{phone}", $about->phone , $text);
        $text = str_replace ("{dostavshik}", $about->dostavshik , $text);
        $text = str_replace ("{t_p}", $about->t_p , $text);
        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }

    public function getInvoiceHtmlText2($model, $id)
    {
        $warehouse = ProductAccount::find()->where(['order_account_id' => $id])->select(['brand_id'])->groupBy(['brand_id'])->all();
        $orderAccount2 = OrderAccount::find()->where(['client_id' => $model->client_id])->one();
        $about = About::find()->where(['id' => 1])->one();
        $table = '';
        $allCount = 0;
        $allSumm = 0;
        
        $table .= '<table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
                    <tr style="background-color:#a0d9ea;" >
                        <td style="height: 20px;text-align: center; width: 15%; border: 1px solid #000;"><b>JOY</b></td>
                        <td style="height: 20px;text-align: center; width: 15%; border: 1px solid #000;"><b>MODEL</b></td>
                        <td style="height: 20px;text-align: center; width: 15%; border: 1px solid #000;"><b>NOMI</b></td>
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>TIP</b></td>
                        
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>SONI</b></td>
                    </tr>';
        foreach ($warehouse as $model1) { 
            foreach ($orderProduct = ProductAccount::find()->andWhere(['order_account_id' => $id])->andWhere(['brand_id' => $model1->brand_id])->all() as $model1){ 
                $type_color = $model1->type_sklad_id ==1?'<tr style="background-color:#67a38569">':'<tr style="">';
                $table .= $type_color.'
                            <td style="height: 20px; border: 1px solid #000;"><b>&nbsp;'. $model1->typeSklad->name . '</b></td>
                            <td style="height: 20px; border: 1px solid #000;"><b>&nbsp;'. $model1->brand->name . '</b></td>
                            <td style="height: 20px; border: 1px solid #000;"><b>&nbsp;'. $model1->productCategory->name.($model1->size!='0'?'&nbsp; (&nbsp;'. $model1->size.'&nbsp;)' : '') . '</b></td>
                            <td style="height: 20px; width: 100px; border: 1px solid #000;"><b>&nbsp;'. $model1->getTypeView($model1->type) . '</b></td>
                            
                            <td style="height: 20px; text-align: center; border: 1px solid #000;"><b>'. $model1->count . '</b></td>
                        </tr>';
                $allCount = $allCount + $model1->count;
                $allSumm = $allSumm + $model1->count * $model1->price;
            }
            // $table .= '<tr style="">
            //                 <td colspan="5" style="height: 20px; border: 1px solid #000;">&nbsp;</td>
                            
            //             </tr>';
        }
        $table .= '
                    <tr style="">
                        <td colspan="4" style=";height: 20px; border: 1px solid #000;">&nbsp;<b>Jami</b></td>

                        <td style="height: 20px; text-align: center; border: 1px solid #000;"><b></b></td>
                    </tr>
        </table>';

        $text = '   
          
        <p style="width: 100%; margin-top: -10px; text-align: center;"><b>Buyurtma sanasi:</b> {order_number} <br> <b>Mijoz:</b>  {customer_fio}<br> <b>Mijoz Telefon raqami:</b>  {customer_phone}</p>  
        '.$table.'<table style="margin-top: 30px; width: 100%;">
        <tr>
            <td style="width: 35%; padding-left: 0;">Mahsulotlarni yig\'uvchi xodim: </td>
            <td style="width: 65%; text-align: left; border-bottom: 1px solid #000;"></td>
        </tr>
    </table> 
    <table style="margin-top: 30px; width: 100%;">
        <tr>
            <td style="width: 35%; padding-left: 0;">Shafyor: </td>
            <td style="width: 65%; text-align: left; border-bottom: 1px solid #000;"></td>
        </tr>
    </table> 
  ';
        
        $text = str_replace ("{exchange_rate}", $model->exchange_rate , $text);
        $text = str_replace ("{all_total_debt}", Yii::$app->formatter->asDecimal($orderAccount2->total_debt,2), $text);
        $text = str_replace ("{total_debt}", Yii::$app->formatter->asDecimal($model->total_debt,2) , $text);
        $text = str_replace ("{discount_amount}", $model->discount_amount , $text);
        $text = str_replace ("{sum_dollar}", Yii::$app->formatter->asDecimal($model->sum_dollar,2) , $text);
        $text = str_replace ("{all_summ_dollar}", Yii::$app->formatter->asDecimal($model->all_summ_dollar,2) , $text);
        $text = str_replace ("{sum_som}", Yii::$app->formatter->asDecimal($model->sum_som,2) , $text);
        $text = str_replace ("{sum_transfers}", Yii::$app->formatter->asDecimal($model->sum_transfers,2) , $text);
        $text = str_replace ("{sum_cart}", Yii::$app->formatter->asDecimal($model->sum_cart, 2) , $text);
        $text = str_replace ("{all_product_sum}", Yii::$app->formatter->asDecimal($model->all_product_sum, 2) , $text);
        $text = str_replace ("{date}", $model->date , $text);
        

        $text = str_replace ("{order_number}", $model->date , $text);
        $text = str_replace ("{customer_fio}", $model->client->fio , $text);
        $text = str_replace ("{customer_phone}", $model->client->phone , $text);
        $text = str_replace ("{customer_region}", $model->client->region_id?$model->client->region->name:'' , $text);
        $text = str_replace ("{customer_district}", $model->client->district_id?$model->client->district->name:'' , $text);

        $text = str_replace ("{nomer_nakladnoy}", $about->nomer_nakladnoy , $text);
        $text = str_replace ("{postavshik}", $about->postavshik , $text);
        $text = str_replace ("{phone}", $about->phone , $text);
        $text = str_replace ("{dostavshik}", $about->dostavshik , $text);
        $text = str_replace ("{t_p}", $about->t_p , $text);

        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }
}