<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "price_product".
 *
 * @property int $id
 * @property int $brand_id Brands
 * @property int $product_category_id Product category
 * @property double $real_price Size
 * @property string $cr_date
 *
 * @property Brands $brand
 * @property ProductCategory $productCategory
 */
class PriceProduct extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'price_product';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['brand_id', 'product_category_id', 'type'], 'integer'],
            [['real_price', 'size', 'count'], 'number'],
            [['cr_date'], 'safe'],
            [['brand_id'], 'exist', 'skipOnError' => true, 'targetClass' => Brands::className(), 'targetAttribute' => ['brand_id' => 'id']],
            [['product_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProductCategory::className(), 'targetAttribute' => ['product_category_id' => 'id']],
            [['brand_id', 'product_category_id'],'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'brand_id' => 'Model',
            'size' => 'O\'lchami',
            'product_category_id' => 'Nomi',
            'real_price' => 'Narxi ($)',
            'cr_date' => 'Narx o\'zgargan sana',
            'type' => 'Tip',
            'count' => 'Soni',
        ];
    }
    public function beforeSave($insert)
    {   
        $this->cr_date = date('Y-m-d H:i:s');
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBrand()
    {
        return $this->hasOne(Brands::className(), ['id' => 'brand_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductCategory()
    {
        return $this->hasOne(ProductCategory::className(), ['id' => 'product_category_id']);
    }

    public  function getBrands()
    {
        return ArrayHelper::map(Brands::find()->where(['sup_status' => 1])->all(), 'id', 'name');
    }
    public static function getBrandsList($ids = [])
    {
        return \yii\helpers\ArrayHelper::map(Brands::find()->where(['sup_status' => 1])->all(), 'id', 'name');
    }
    public function getUpdateBrands()
    {
        return ArrayHelper::map(Brands::find()->all(), 'id', 'name');
    }
    public function getProductCategories()
    {
        return ArrayHelper::map(ProductCategory::find()->where(['sup_status' => 1])->all(), 'id', 'name');
    }
    
    public function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }
    public function getTypeView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }
}
