<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property int $permission Роль
 * @property string $username Логин
 * @property int $status Статус пользователя
 * @property string $email Email
 * @property string $password Пароль
 * @property string $avatar Аватар
 * @property string $surname Фамилия
 * @property string $name Имя
 * @property string $middle_name Отчество
 * @property string $phone Телефон номер
 * @property string $last_seen Последное активнос
 * @property string $access_token Токен
 * @property string $registry_date Дата регистраци
 * @property bool $email_verified  E-mail Верифицирован
 * @property bool $phone_verified Телефон номер Верифицирован
 * @property int $referal_id Рефералный пользователь
 */
class Users extends \yii\db\ActiveRecord
{

    /**
     * super admin id si
     */
    const SUPER_ADMIN_ID = 1;


    /**
     *  rollar qiyamti
     */
    const ADMIN = 1;
    const MENEJER = 2;
    const WORKER = 3;
    const CLIENT = 4;
    const OMBOR_MENEJER = 5;
    const SUPER_MENEJER = 6;
    const SELLER = 7;


    /**
     * role value description
     */
    const ADMIN_DESC = "Administrator";
    const MENEJER_DESC = "Menejer";
    const WORKER_DESC = "Xodim";
    const CLIENT_DESC = "Mijoz";
    const OMBOR_MENEJER_DESC = "Ombor Menejeri";
    const SUPER_MENEJER_DESC = "Bosh Menejer";
    const SELLER_DESC = "Sotuvchi";

    /**
     * statuslar qiymatlari
     */
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 2;
    const STATUS_BLOCKED = 3;
    const STATUS_DELETE  = 4;


    /**
     * statuslarni descriptioni
     */
    const STATUS_ACTIVE_DESC = "Faol";
    const STATUS_INACTIVE_DESC = "Faol emas";
    const STATUS_BLOCKED_DESC = "Bloklangan";
    const STATUS_DELETE_DESC  = "Oʻchirilgan";

    const DIR_IMAGE = 'avatars';


    /**
     * yordamchi ozgaruvchilar
     * @var
     */
    public $image;
    public $new_password;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'users';
    }


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['permission', 'status', 'referal_id', 'type'], 'integer'],
            [['last_seen', 'registry_date','image','new_password'], 'safe'],
            [['email_verified', 'phone_verified'], 'boolean'],
            [['username', 'address', 'email', 'password', 'avatar', 'surname', 'name', 'middle_name', 'phone', 'access_token'], 'string', 'max' => 255],
            [['email','username'] ,'unique'],
            [['email'],'email'],
            [['permission' ,'username','phone','password','surname','name', 'type'],'required'],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'permission' => 'Rol',
            'address' => 'Manzil',
            'username' => 'Login',
            'status' => 'Status',
            'email' => 'Email',
            'password' => 'Parol',
            'avatar' => 'Rasm',
            'surname' => 'Familiya',
            'name' => 'Ism',
            'middle_name' => 'Otasining ismi',
            'phone' => 'Telefon nomer',
            'last_seen' => 'Oxirgi faolligi',
            'access_token' => 'Токен',
            'registry_date' => 'Ro\'yxatdan o\'tgan sana',
            'email_verified' => ' E-mail Верифицирован',
            'phone_verified' => 'Телефон номер Верифицирован',
            'referal_id' => 'Рефералный пользователь',
            'type' => 'Turi',
            'image' => 'Rasm',
            'new_password' => 'Yangi parol',
        ];
    }


    /**
     * sqlashdan oldingi methodlar
     * @param bool $insert
     * @return bool
     */
    public function beforeSave($insert)
    {

        if ($this->isNewRecord)
        {
            $this->registry_date = date("Y-m-d H:i");
            $this->status = self::STATUS_ACTIVE;
            // $this->permission = self::WORKER;
            $user = Yii::$app->user->identity;
            $this->password = Yii::$app->security->generatePasswordHash($this->password);
            // $this->username = self::Unikal();
            $this->access_token = Yii::$app->getSecurity()->generateRandomString();
        }

        $this->phone = str_replace("-","",$this->phone);
        if($this->new_password != null) $this->password = Yii::$app->security->generatePasswordHash($this->new_password);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * unikalni usrname berish
     * @return string
     * @throws \yii\db\Exception
     */
    public static function Unikal(){
        do{
            $rand = "u".random_int(1000000000,9999999999);
            $base = Yii::$app->db->createCommand("SELECT * FROM users WHERE username='".$rand."'")->queryOne();
        }while($base != false);
        return $rand;
    }


    public function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Do\'kom sotuvchisi',],
            ['id' => '2', 'type' => 'Sklad sotuvchisi',],
            ['id' => '3', 'type' => 'Dastavka sotuvchisi',],
        ],
        'id', 'type');
    }

    public function getTypeView($id)
    {
        if($id == 1) return 'Do\'kom sotuvchisi';
        if($id == 2) return 'Sklad sotuvchisi';
        if($id == 3) return 'Dastavka sotuvchisi';
    }

    public function getTypeNameView($name)
    {
        if($name == 'Do\'kom sotuvchisi') return 1;
        if($name == 'Sklad sotuvchisi') return 2;
        if($name == 'Dastavka sotuvchisi') return 3;
    }

    /**
     * fio sini olish
     * @return string
     */
    public function getFio(){
        return $this->surname . " " . $this->name . " " . $this->middle_name;
    }


    /**
     * userni rollarini listini olish
     * @return string[]
     */
    public static function getRole(){
        return [
            self::ADMIN => self::ADMIN_DESC,
            self::MENEJER => self::MENEJER_DESC,
            self::WORKER => self::WORKER_DESC,
            self::CLIENT => self::CLIENT_DESC,
            self::OMBOR_MENEJER => self::OMBOR_MENEJER_DESC,
            self::SUPER_MENEJER => self::SUPER_MENEJER_DESC,
            self::SELLER => self::SELLER_DESC,
        ];
    }


    /**
     * rollarni descriptioni
     * @return string
     */
    public function getRoleDescription(){
        switch ($this->permission){
            case self::ADMIN : return  self::ADMIN_DESC;
            case self::MENEJER : return  self::MENEJER_DESC;
            case self::WORKER : return  self::WORKER_DESC;
            case self::CLIENT : return  self::CLIENT_DESC;
            case self::OMBOR_MENEJER : return  self::OMBOR_MENEJER_DESC;
            case self::SUPER_MENEJER : return  self::SUPER_MENEJER_DESC;
            case self::SELLER : return  self::SELLER_DESC;
            default : return "Неизвестно";
        }
    }


    /**
     * status listini olish
     * @return array[]
     */
    public static function getStatus(){
        return [
            self::STATUS_ACTIVE => self::STATUS_ACTIVE_DESC,
            self::STATUS_INACTIVE => self::STATUS_INACTIVE_DESC,
            self::STATUS_BLOCKED => self::STATUS_BLOCKED_DESC,
            self::STATUS_DELETE => self::STATUS_DELETE_DESC,
        ];
    }


    /**
     * statusni descrtiptionini olish
     * @return string
     */
    public function getStatusDescription(){
        switch ($this->status){
            case self::STATUS_ACTIVE : return  self::STATUS_ACTIVE_DESC;
            case self::STATUS_INACTIVE : return  self::STATUS_INACTIVE_DESC;
            case self::STATUS_BLOCKED : return  self::STATUS_BLOCKED_DESC;
            case self::STATUS_DELETE : return  self::STATUS_DELETE_DESC;
            default : return "Неизвестно";
        }
    }


    /**
     * user rasmini urlni olish
     * @return string
     */
    public function getAvatar()
    {
        if ($this->avatar == ''){
            return '/web/img/nouser.png';
        }else{
            return Yii::$app->params['siteName']   . "/web/uploads/" . self::DIR_IMAGE . "/" . $this->avatar;
        }
    }


    /**
     * userga rasm yuklash
     * @throws \yii\db\Exception
     */
    public function upload()
    {
        $fileName = $this->id . '-' . Yii::$app->security->generateRandomString() . '.' . $this->image->extension;
        if(!empty($this->image))
        {
            if(file_exists('uploads/avatars/'.$this->avatar) && $this->avatar != null)
            {
                unlink('uploads/avatars/'.$this->avatar);
            }

            $this->image->saveAs('uploads/avatars/'.$fileName);
            Yii::$app->db->createCommand()->update('users', ['avatar' => $fileName], [ 'id' => $this->id ])->execute();
        }
    }

    public static function isAdminRight($id)
    {
        return self::findOne($id)->permission == 1;
    }

    public static function isMenejerRight($id)
    {
        return self::findOne($id)->permission == 1 or self::findOne($id)->permission == 2 or self::findOne($id)->permission == 5 or self::findOne($id)->permission == 6 or self::findOne($id)->permission == 7;
    }

    public static function isWorkerRight($id)
    {
        return self::findOne($id)->permission == 1 or self::findOne($id)->permission == 2 or self::findOne($id)->permission == 3 or self::findOne($id)->permission == 5 or self::findOne($id)->permission == 7;
    }

    public static function isClientRight($id)
    {
        return self::findOne($id)->permission == 1 or self::findOne($id)->permission == 2 or self::findOne($id)->permission == 3 or self::findOne($id)->permission == 4 or self::findOne($id)->permission == 5 or self::findOne($id)->permission == 7;
    }
}
