<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;
use app\models\TypeSklad;
/**
 * This is the model class for table "vozvrat_order".
 *
 * @property int $id
 * @property int $client_id client
 * @property string $date
 * @property double $exchange_rate dollar exchange rate
 * @property double $discount_amount сумма скидки
 * @property double $summ_dollar summ_dollar
 * @property double $all_summ_dollar all_summ_dollar
 * @property double $total_debt total debt
 * @property int $confirmation Confirmation
 * @property string $cr_date_time
 * @property string $comment Comment
 * @property int $created_by create user
 *
 * @property ProductAccount[] $productAccounts
 * @property ProductAccountHistory[] $productAccountHistories
 * @property Users $createdBy
 */
class VozvratOrder extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'vozvrat_order';
    }

    /**
     * {@inheritdoc}
     */
    var $comments = '';

    public function rules()
    {
        return [
            [['client_id', 'confirmation', 'created_by', 'update_status'], 'integer'],
            [['date', 'cr_date_time'], 'safe'],
            [['exchange_rate', 'discount_amount', 'sum_dollar', 'sum_som', 'sum_cart', 'all_summ_dollar', 'total_debt', 'old_total_debt', 'large_price', 'is_delete', 'product_summ_dollar'], 'number'],
            [['comment'], 'string'],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => Client::className(), 'targetAttribute' => ['client_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_id' => 'Mijoz',
            'date' => 'Sana',
            'exchange_rate' => 'Dollar kursi',
            'discount_amount' => 'Jami chegirma ($)',
            'sum_dollar' => 'Summa ($)',
            'sum_som' => 'Summa so\'m',
            'sum_cart' => 'Summa karta',
            'all_summ_dollar' => 'Mijozga qaytarilgan summa ($)',
            'total_debt' => 'Umumiy qarz ($)',
            'old_total_debt' => 'Oldingi umumiy qarz ($)',
            'product_summ_dollar' => 'Qaytgan mahsulot summasi ($)',
            'confirmation' => '',
            'cr_date_time' => 'Yaratilgan vaqti',
            'comment' => 'Izoh',
            'comments' => 'Izoh',
            'created_by' => 'Xodim',
            'large_price' => 'Narx farqi',
            'is_delete' => 'O\'chirilganmi',
            'update_status' => 'Yangilash holati',
        ];
    }

    public function beforeSave($insert)
    {   
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductAccounts()
    {
        return $this->hasMany(ProductAccount::className(), ['vozvrat_order_id' => 'id']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductAccountHistories()
    {
        return $this->hasMany(ProductAccountHistory::className(), ['vozvrat_order_id' => 'id']);
    }

    public function getClient()
    {
        return $this->hasOne(Client::className(), ['id' => 'client_id']);
    }
    public function getClients()
    {
        return ArrayHelper::map(Client::find()->all(), 'id', 'fio');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

        public function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }

    public function getTypeNameView($name)
    {
        if($name == 'Dona') return 1;
        if($name == 'Karobka') return 2;
        if($name == 'Komplekt') return 3;
        if($name == 'Pochka') return 4;
    }
    
    public function getTypeView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }
    public function getTypeSklads()
    {
        return ArrayHelper::map(TypeSklad::find()->all(), 'id', 'name');
    }


    public function getInvoiceHtmlText($model, $id)
    {
        $warehouse = ProductAccountHistory::find()->where(['vozvrat_order_id' => $id])->select(['brand_id'])->groupBy(['brand_id'])->all();
        $orderAccount2 = OrderAccount::find()->where(['client_id' => $model->client_id])->one();
        $about = About::find()->where(['id' => 1])->one();
        $sum = (float) KeshbekHistory::find()->where(['client_id' => $model->client_id])->sum('keshbek_sum');
        $debtRepayments = DebtRepayment::find()
            ->where(['date' => $model->date])
            ->andWhere(['client_id' => $model->client_id])
            ->andWhere(['or',
        ['!=', 'is_worker', 1],
        ['is', 'is_worker', null]
            ])
            ->all();

        $debtRepaymentall = 0;
        foreach ($debtRepayments as $value) { 
            $debtRepaymentall = $debtRepaymentall + $value->all_summ_dollar;
        }

        $table = '';
        $allCount = 0;
        $allSumm = 0;
        $tulan_sum_som = $model->sum_som?'To\'langan summa so\'mda:': '';
        $tulan_sum_karta = $model->sum_cart?'To\'langan summa kartada:': '';
        $discount_amount_sum = $model->discount_amount?'Jami chegirma ($):': '';
        $discount_amount_sum_val = $model->discount_amount?$model->discount_amount.' $,': '';
        $debtRepaymentall_sum = $debtRepaymentall != 0 ?'To\'langan qarz ($):': '';
        $debt_repayment_all = $debtRepaymentall != 0 ?$debtRepaymentall.' $,': '';
        if($sum>0){
            $keshbek_tr = '<tr> <td colspan="4" style="text-align: center;"><b style="font-size:16px;color:green">Keshbek: '.Yii::$app->formatter->asDecimal($sum, 2).'$</b></td> </tr>';
        }else{
            $keshbek_tr = '';
        }
        

        $table .= '<table style="width: 100%; border-collapse: collapse; margin-top: 15px;font-size:12px">
                    <tr style="">
                        <td style="height: 20px;text-align: center; width: 10px; border: 1px solid #000;"><b>№</b></td>
                        <td style="height: 15px;text-align: center; width: 15%; border: 1px solid #000;"><b>MODEL</b></td>
                        <td style="height: 15px;text-align: center; width: 15%; border: 1px solid #000;"><b>NOMI</b></td> 
                        <td style="height: 15px;text-align: center; width: 10%; border: 1px solid #000;"><b>SONI</b></td>   
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>TIP</b></td>                    
                        <td style="height: 15px;text-align: center; width: 10%; border: 1px solid #000;"><b>NARXI ($)</b></td>
                        <td style="height: 15px;text-align: center; width: 12%; border: 1px solid #000;"><b>UMUMIY NARXI ($)</b></td>
                    </tr>';
        $i =1;
        foreach ($warehouse as $model1) { 
            
            foreach ($orderProduct = ProductAccountHistory::find()->andWhere(['vozvrat_order_id' => $id])->andWhere(['brand_id' => $model1->brand_id])->all() as $model1){ 
                $table .= '<tr style="">
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $i . '</b></td>
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $model1->brand->name . '</b></td>
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $model1->productCategory->name.($model1->size!='0'?'&nbsp; (&nbsp;'. $model1->size.'&nbsp;)' : '') . '</b></td>
                            <td style="height: 15px; text-align: center; border: 1px solid #000;"><b>'. $model1->count . '</b></td>
                            <td style="height: 15px; text-align: center;  border: 1px solid #000;"><b>&nbsp;'. $model1->getTypeView($model1->type) . '</b></td>
                            <td style="height: 15px; text-align: center;  border: 1px solid #000;"><b>'. $model1->price . '</b></td>
                            <td style="height: 15px; text-align: left;  border: 1px solid #000;"><b> = '. round($model1->count * $model1->price,2) . '</b></td>
                        </tr>';
                $allCount = $allCount + $model1->count;
                $allSumm = $allSumm + $model1->count * $model1->price;
                $i=$i+1;
            }
            // $table .= '<tr style="">
            //                 <td colspan="6" style="height: 20px; border: 1px solid #000;">&nbsp;</td>
                            
            //             </tr>';
        }
        $table .= '
                    <tr style="">
                        <td colspan="4" style=";height: 20px; border: 1px solid #000;">&nbsp;<b>Jami</b></td>

                        <td style="height: 15px; text-align: center; border: 1px solid #000;"><b></b></td>
                        <td style=";height: 15px;text-align: center; border: 1px solid #000;">&nbsp;-</td>
                        <td style=";height: 15px; border: 1px solid #000;">&nbsp;&nbsp;&nbsp;<b>'. round($allSumm,2) . '</b></td>
                    </tr>
        </table>';

        $text = '   
          
        <table style="width: 100%; text-align: right; font-size:12px">  
             <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px;">{cr_date_time} </b><b style="font-size:20px;">sanadagi vozvrat tavarlar</b><br/></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px; color:red;">{customer_fio}<br/></b></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><hr></td>
            </tr>
            <tr>
                <td rowspan="5" style="text-align: left; width: 150px!important;"><img src="../views/image/logo-1.png" style="height:100px; border-radius:20%;"></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 200px;">Do\'kon:</th>
                <td  ><b >{t_p},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;font-size:14px; color:green;">Dollar kursi:</th>
                <td ><b style="text-align: left;font-size:14px; color:green;">{exchange_rate} so\'m</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left;">Firma:</th>
                <td ><b >{postavshik},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left; width: 150px;">Manzil:</th>
                <td ><b >{customer_region}, {customer_district}</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 150px;">Telefon nomer1:</th>
                <td ><b >{phone},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;">Telefon:</th>
                <td   ><b >{customer_phone}</b></td>
            </tr>
           
        </table>
        '.$table.'<br>
        <table style="width: 100%; text-align: right; font-size:12px;">   
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 250px;color:#f59c1">Ostatka  ($):</th>
                    <td ><b style="font-size:16px;color:#f59c1">{total_debt_old} $,</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0">Qaytarilgan summa dollarda ($):</th>
                    <td ><b style="color:#474ba0">{sum_dollar} $</b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px; color:#f59c1">Vozvrat tavarlar summasi ($):</th>
                    <td ><b style="color:#f59c1">{all_product_sum} $,</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0">Qaytarilgan summa so\'mda:</th>
                    <td ><b style="color:#474ba0">{sum_som} </b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;color:#f59c1">Jami qaytarilgan summa ($):</th>
                    <td ><b style="color:#f59c1" >{all_summ_dollar} $,</b></td>
        
                    <td style="width: 10px;"></td>
                    <th nowrap style="text-align: left; color:#474ba0">Qaytarilgan summa kartada:</th>
                    <td ><b style="color:#474ba0">{sum_cart} </b></td>
                </tr>
                <tr>
                    <th nowrap style="text-align: left; width: 150px;color:#f59c1">'.$discount_amount_sum.'</th>
                    <td ><b style="color:#f59c1" >'.$discount_amount_sum_val.'</b></td>
                </tr>
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 150px;color:red">Qolgan qarz ($): </th>
                    <td ><b style="font-size:16px;color:red" >{all_total_debt} $,</b></td>
                    
                </tr>
            </table> 
      ';

        $text = str_replace ("{exchange_rate}", $model->exchange_rate , $text);
        $text = str_replace ("{total_debt_old}", Yii::$app->formatter->asDecimal($model->old_total_debt, 2), $text);
        $text = str_replace ("{all_total_debt}", Yii::$app->formatter->asDecimal($orderAccount2->total_debt,2), $text);
        $text = str_replace ("{total_debt}", Yii::$app->formatter->asDecimal($model->total_debt,2) , $text);
        $text = str_replace ("{discount_amount}", $model->discount_amount?$model->discount_amount:'' , $text);
        $text = str_replace ("{sum_dollar}", $model->sum_dollar?Yii::$app->formatter->asDecimal($model->sum_dollar,2):'0' , $text);
        $text = str_replace ("{all_summ_dollar}", Yii::$app->formatter->asDecimal($model->all_summ_dollar,2) , $text);
        $text = str_replace ("{sum_som}", $model->sum_som?Yii::$app->formatter->asDecimal($model->sum_som,2):' ' , $text);
        $text = str_replace ("{sum_cart}", $model->sum_cart?Yii::$app->formatter->asDecimal($model->sum_cart, 2):'0' , $text);
        $text = str_replace ("{all_product_sum}", $model->product_summ_dollar?Yii::$app->formatter->asDecimal($model->product_summ_dollar, 2):'0' , $text);
        $text = str_replace ("{date}", $model->date , $text);
        $text = str_replace ("{debt_repayment_all}", Yii::$app->formatter->asDecimal($debtRepaymentall, 2), $text);
        $text = str_replace ("{cr_date_time}", date('d.m.Y', strtotime($model->cr_date_time)) , $text);

        $text = str_replace ("{order_number}", $model->date , $text);
        $text = str_replace ("{customer_fio}", $model->client->fio , $text);
        $text = str_replace ("{customer_phone}", $model->client->phone , $text);
        $text = str_replace ("{customer_region}", $model->client->region_id?$model->client->region->name:'' , $text);
        $text = str_replace ("{customer_district}", $model->client->district_id?$model->client->district->name:'' , $text);

        $text = str_replace ("{nomer_nakladnoy}", $about->nomer_nakladnoy , $text);
        $text = str_replace ("{postavshik}", $about->postavshik , $text);
        $text = str_replace ("{phone}", $about->phone , $text);
        $text = str_replace ("{dostavshik}", $about->dostavshik , $text);
        $text = str_replace ("{t_p}", $about->t_p , $text);

        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }

    public function getInvoiceHtmlTextForClient($model, $id)
    {
        $warehouse = ProductAccountHistory::find()->where(['vozvrat_order_id' => $id])->select(['brand_id'])->groupBy(['brand_id'])->all();
        $orderAccount2 = OrderAccount::find()->where(['client_id' => $model->client_id])->one();
        $about = About::find()->where(['id' => 1])->one();
        $sum = (float) KeshbekHistory::find()->where(['client_id' => $model->client_id])->sum('keshbek_sum');
        $debtRepayments = DebtRepayment::find()
            ->where(['date' => $model->date])
            ->andWhere(['client_id' => $model->client_id])
            ->andWhere(['or',
        ['!=', 'is_worker', 1],
        ['is', 'is_worker', null]
            ])
            ->all();

        $debtRepaymentall = 0;
        foreach ($debtRepayments as $value) { 
            $debtRepaymentall = $debtRepaymentall + $value->all_summ_dollar;
        }

        $table = '';
        $allCount = 0;
        $allSumm = 0;
        $tulan_sum_som = $model->sum_som?'To\'langan summa so\'mda:': '';
        $tulan_sum_karta = $model->sum_cart?'To\'langan summa kartada:': '';
        $discount_amount_sum = $model->discount_amount?'Jami chegirma ($):': '';
        $discount_amount_sum_val = $model->discount_amount?$model->discount_amount.' $,': '';
        $debtRepaymentall_sum = $debtRepaymentall != 0 ?'To\'langan qarz ($):': '';
        $debt_repayment_all = $debtRepaymentall != 0 ?$debtRepaymentall.' $,': '';
        if($sum>0){
            $keshbek_tr = '<tr> <td colspan="4" style="text-align: center;"><b style="font-size:16px;color:green">Keshbek: '.Yii::$app->formatter->asDecimal($sum, 2).'$</b></td> </tr>';
        }else{
            $keshbek_tr = '';
        }
        

        $table .= '<table style="width: 100%; border-collapse: collapse; margin-top: 15px;font-size:12px">
                    <tr style="">
                        <td style="height: 20px;text-align: center; width: 10px; border: 1px solid #000;"><b>№</b></td>
                        <td style="height: 15px;text-align: center; width: 15%; border: 1px solid #000;"><b>MODEL</b></td>
                        <td style="height: 15px;text-align: center; width: 15%; border: 1px solid #000;"><b>NOMI</b></td> 
                        <td style="height: 15px;text-align: center; width: 10%; border: 1px solid #000;"><b>SONI</b></td>   
                        <td style="height: 20px;text-align: center; width: 10%; border: 1px solid #000;"><b>TIP</b></td>                    
                        <td style="height: 15px;text-align: center; width: 10%; border: 1px solid #000;"><b>NARXI ($)</b></td>
                        <td style="height: 15px;text-align: center; width: 12%; border: 1px solid #000;"><b>UMUMIY NARXI ($)</b></td>
                    </tr>';
        $i =1;
        foreach ($warehouse as $model1) { 
            
            foreach ($orderProduct = ProductAccountHistory::find()->andWhere(['vozvrat_order_id' => $id])->andWhere(['brand_id' => $model1->brand_id])->all() as $model1){ 
                $table .= '<tr style="">
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $i . '</b></td>
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $model1->brand->name . '</b></td>
                            <td style="height: 15px; border: 1px solid #000;"><b>&nbsp;'. $model1->productCategory->name.($model1->size!='0'?'&nbsp; (&nbsp;'. $model1->size.'&nbsp;)' : '') . '</b></td>
                            <td style="height: 15px; text-align: center; border: 1px solid #000;"><b>'. $model1->count . '</b></td>
                            <td style="height: 15px; text-align: center;  border: 1px solid #000;"><b>&nbsp;'. $model1->getTypeView($model1->type) . '</b></td>
                            <td style="height: 15px; text-align: center;  border: 1px solid #000;"><b>'. $model1->price . '</b></td>
                            <td style="height: 15px; text-align: left;  border: 1px solid #000;"><b> = '. round($model1->count * $model1->price,2) . '</b></td>
                        </tr>';
                $allCount = $allCount + $model1->count;
                $allSumm = $allSumm + $model1->count * $model1->price;
                $i=$i+1;
            }
            // $table .= '<tr style="">
            //                 <td colspan="6" style="height: 20px; border: 1px solid #000;">&nbsp;</td>
                            
            //             </tr>';
        }
        $table .= '
                    <tr style="">
                        <td colspan="4" style=";height: 20px; border: 1px solid #000;">&nbsp;<b>Jami</b></td>

                        <td style="height: 15px; text-align: center; border: 1px solid #000;"><b></b></td>
                        <td style=";height: 15px;text-align: center; border: 1px solid #000;">&nbsp;-</td>
                        <td style=";height: 15px; border: 1px solid #000;">&nbsp;&nbsp;&nbsp;<b>'. round($allSumm,2) . '</b></td>
                    </tr>
        </table>';

        $text = '   
          
        <table style="width: 100%; text-align: right; font-size:12px">  
             <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px;">{cr_date_time} </b><b style="font-size:20px;">sanadagi vozvrat tavarlar</b><br/></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><b style="font-size:20px; color:red;">{customer_fio}<br/></b></td>
            </tr>
            <tr>
                <td colspan="6" style="text-align: center; width: 150px!important;"><hr></td>
            </tr>
            <tr>
                <td rowspan="5" style="text-align: left; width: 150px!important;"><img src="../views/image/logo-1.png" style="height:100px; border-radius:20%;"></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 200px;">Do\'kon:</th>
                <td  ><b >{t_p},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;font-size:14px; color:green;">Dollar kursi:</th>
                <td ><b style="text-align: left;font-size:14px; color:green;">{exchange_rate} so\'m</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left;">Firma:</th>
                <td ><b >{postavshik},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left; width: 150px;">Manzil:</th>
                <td ><b >{customer_region}, {customer_district}</b></td>
            </tr>
            <tr>
                <th nowrap style="text-align: left; width: 150px;">Telefon nomer1:</th>
                <td ><b >{phone},</b></td>
                <td style="width: 10px;"></td>
                <th nowrap style="text-align: left;">Telefon:</th>
                <td   ><b >{customer_phone}</b></td>
            </tr>
           
        </table>
        '.$table.'<br>
        <table style="width: 100%; text-align: right; font-size:12px;">   
                <tr>
                    <th nowrap style="font-size:16px;text-align: left; width: 250px;color:#f59c1">Ostatka  ($):</th>
                    <td ><b style="font-size:16px;color:#f59c1">{total_debt_old} $,</b></td>
                    
                    <td style="width: 10px;"></td>
                    <th nowrap style="font-size:16px;text-align: left; width: 150px;color:red">Qolgan qarz ($): </th>
                    <td ><b style="font-size:16px;color:red" >{all_total_debt} $,</b></td>
                </tr>
            </table> 
      ';

        $text = str_replace ("{exchange_rate}", $model->exchange_rate , $text);
        $text = str_replace ("{total_debt_old}", Yii::$app->formatter->asDecimal($model->old_total_debt, 2), $text);
        $text = str_replace ("{all_total_debt}", Yii::$app->formatter->asDecimal($orderAccount2->total_debt,2), $text);
        $text = str_replace ("{total_debt}", Yii::$app->formatter->asDecimal($model->total_debt,2) , $text);
        $text = str_replace ("{discount_amount}", $model->discount_amount?$model->discount_amount:'' , $text);
        $text = str_replace ("{sum_dollar}", $model->sum_dollar?Yii::$app->formatter->asDecimal($model->sum_dollar,2):'0' , $text);
        $text = str_replace ("{all_summ_dollar}", Yii::$app->formatter->asDecimal($model->all_summ_dollar,2) , $text);
        $text = str_replace ("{sum_som}", $model->sum_som?Yii::$app->formatter->asDecimal($model->sum_som,2):' ' , $text);
        $text = str_replace ("{sum_cart}", $model->sum_cart?Yii::$app->formatter->asDecimal($model->sum_cart, 2):'0' , $text);
        $text = str_replace ("{all_product_sum}", $model->product_summ_dollar?Yii::$app->formatter->asDecimal($model->product_summ_dollar, 2):'0' , $text);
        $text = str_replace ("{date}", $model->date , $text);
        $text = str_replace ("{debt_repayment_all}", Yii::$app->formatter->asDecimal($debtRepaymentall, 2), $text);
        $text = str_replace ("{cr_date_time}", date('d.m.Y', strtotime($model->cr_date_time)) , $text);

        $text = str_replace ("{order_number}", $model->date , $text);
        $text = str_replace ("{customer_fio}", $model->client->fio , $text);
        $text = str_replace ("{customer_phone}", $model->client->phone , $text);
        $text = str_replace ("{customer_region}", $model->client->region_id?$model->client->region->name:'' , $text);
        $text = str_replace ("{customer_district}", $model->client->district_id?$model->client->district->name:'' , $text);

        $text = str_replace ("{nomer_nakladnoy}", $about->nomer_nakladnoy , $text);
        $text = str_replace ("{postavshik}", $about->postavshik , $text);
        $text = str_replace ("{phone}", $about->phone , $text);
        $text = str_replace ("{dostavshik}", $about->dostavshik , $text);
        $text = str_replace ("{t_p}", $about->t_p , $text);

        $text = str_replace ("{cr_date}", date(' d/m/Y H:i:s') , $text);
        return $text;
    }
}
