<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;

/**
 * This is the model class for table "warehouse_history".
 *
 * @property int $id
 * @property int $brand_id Brands
 * @property int $product_category_id Product category
 * @property double $size Size
 * @property int $count Count
 * @property string $cr_date
 * @property int $created_by create user
 * @property int $update_by update user
 *
 * @property Brands $brand
 * @property Users $createdBy
 * @property ProductCategory $productCategory
 * @property Users $updateBy
 */
class WarehouseHistory extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'warehouse_history';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['brand_id', 'product_category_id', 'count', 'created_by', 'update_by', 'sklad_id', 'type'], 'integer'],
            [['size', 'price'], 'number'],
            [['cr_date', 'cr_date_time'], 'safe'],
            [['brand_id'], 'exist', 'skipOnError' => true, 'targetClass' => Brands::className(), 'targetAttribute' => ['brand_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['product_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProductCategory::className(), 'targetAttribute' => ['product_category_id' => 'id']],
            [['update_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['update_by' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'brand_id' => 'Model',
            'product_category_id' => 'Nomi',
            'size' => 'O\'lchami',
            'price' => 'Narx ($)',
            'count' => 'Soni',
            'cr_date' => 'Sana',
            'created_by' => 'Kim yaratdi',
            'update_by' => 'Kim o\'zgartirdi',
            'type' => 'Tip',
        ];
    }

    public function beforeSave($insert)
    {   
        $this->cr_date = date('Y-m-d H:i:s');
        $this->cr_date_time = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function getProductType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }
    
    public function getProductTypeView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }

    public function getTypeNameView($name)
    {
        if($name == 'Dona') return 1;
        if($name == 'Karobka') return 2;
        if($name == 'Komplekt') return 3;
        if($name == 'Pochka') return 4;
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBrand()
    {
        return $this->hasOne(Brands::className(), ['id' => 'brand_id']);
    }

    public function getBrands()
    {
        return ArrayHelper::map(Brands::find()->all(), 'id', 'name');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductCategory()
    {
        return $this->hasOne(ProductCategory::className(), ['id' => 'product_category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdateBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'update_by']);
    }

    public function getYearsList()
    {
        $result = [
            2018 => "2018",
            2019 => "2019",
            2020 => "2020",
            2021 => "2021",
            2022 => "2022",
            2023 => "2023",
            2024 => "2024",
            2025 => "2025",
            2026 => "2026",
            2027 => "2027",
            2028 => "2028",
            2029 => "2029",
            2030 => "2030",
        ];
        return $result;
    }
}
