<?php

namespace app\models;
use yii\helpers\ArrayHelper;
use Yii;
use app\models\Consignor;
/**
 * This is the model class for table "warehouse".
 *
 * @property int $id
 * @property int $brand_id Brands
 * @property int $product_category_id Product category
 * @property double $size Size
 * @property int $count Count
 * @property string $cr_date
 * @property int $created_by create user
 * @property int $update_by update user
 *
 * @property Brands $brand
 * @property Users $createdBy
 * @property ProductCategory $productCategory
 * @property Users $updateBy
 */
class Warehouse extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'warehouse';
    }

    /**
     * {@inheritdoc}
     */
    var $consignor_id = null;
    var $comment = null;
    
    public function rules()
    {
        return [
            [['brand_id', 'product_category_id', 'count', 'created_by', 'update_by', 'type'], 'integer'],
            [['size', 'price', 'all_sum_dollar', 'all_discount_amount', 'all_my_total_debt', 'worker_price'], 'number'],
            [['cr_date'], 'safe'],
            [['status_count'], 'boolean'],
            [['brand_id'], 'exist', 'skipOnError' => true, 'targetClass' => Brands::className(), 'targetAttribute' => ['brand_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['product_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProductCategory::className(), 'targetAttribute' => ['product_category_id' => 'id']],
            [['update_by'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['update_by' => 'id']],
            [['brand_id', 'product_category_id', 'count', 'type'],'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'brand_id' => 'Model',
            'product_category_id' => 'Nomi',
            'size' => 'O\'lchami',
            'price' => 'Haqiqiy Narxi ($)',
            'worker_price' => 'Ishchi Uchun Narx ($)',
            'count' => 'Soni',
            'cr_date' => 'Sana',
            'created_by' => 'Kim yaratdi',
            'update_by' => 'Kim o\'zgartirdi',
            'consignor_id' => 'Yuk jo\'natuvchi',
            'all_sum_dollar' => 'Umumiy to\'langan summa ($)',
            'all_discount_amount' => 'Umumiy qilinga chegirma ($)',
            'all_my_total_debt' => 'Mening ymumiy qarzim ($)',
            'type' => 'Tip',
            'comment' => 'Izoh',
            'status_count' => '',
        ];
    }
    
    public function beforeSave($insert)
    {   
        $this->cr_date = date('Y-m-d H:i:s');
        if ($this->isNewRecord){
            $this->created_by = Yii::$app->user->identity->id;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public static function getStatusCountView($id)
    {
        if($id == 0) return 'Tasdiqlanmagan';
        if($id == 1) return 'Tasdiqlangan';
    }

    public static function getStatusCount()
    {
        return ArrayHelper::map([
            ['id' => '0', 'type' => 'Tasdiqlanmagan',],
            ['id' => '1', 'type' => 'Tasdiqlangan',],
        ],
        'id', 'type');
    }

    public static function getProductTypeForWH()
    {
        return ArrayHelper::map([
            ['id' => '2', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '2', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }

    public static function getProductTypeForClient()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }

    public static function getProductClientType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }

    public static function getProductType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }
    
    public function getProductTypeForClientView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }

    public function getProductTypeView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBrand()
    {
        return $this->hasOne(Brands::className(), ['id' => 'brand_id']);
    }

    public function getBrands()
    {
        return ArrayHelper::map(Brands::find()->all(), 'id', 'name');
    }

    public function getConsignor()
    {
        return ArrayHelper::map(Consignor::find()->all(), 'id', 'name');
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductCategory()
    {
        return $this->hasOne(ProductCategory::className(), ['id' => 'product_category_id']);
    }

    public function getProductCategories()
    {
        return ArrayHelper::map(ProductCategory::find()->all(), 'id', 'name');
    }
    // public function getProductCategories($id)
    // {
    //     return ArrayHelper::map(ProductCategory::find()->where(['brand_id' => $id])->all(), 'id', 'name');
    // }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdateBy()
    {
        return $this->hasOne(Users::className(), ['id' => 'update_by']);
    }

    public function getType()
    {
        return ArrayHelper::map([
            ['id' => '1', 'type' => 'Dona',],
            ['id' => '2', 'type' => 'Karobka',],
            ['id' => '3', 'type' => 'Komplekt',],
            ['id' => '4', 'type' => 'Pochka',],
        ],
        'id', 'type');
    }
    public function getTypeView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }
    public function getTypeClientView($id)
    {
        if($id == 1) return 'Dona';
        if($id == 2) return 'Karobka';
        if($id == 3) return 'Komplekt';
        if($id == 4) return 'Pochka';
    }
}
